(() => {
  // Navigation is centrally generated by script.js so every page stays consistent.
  const path=location.pathname.replace(/\/$/,'').split('/').pop()||'index';
  if(path==='events'||path==='events.html'){
    document.querySelectorAll('.more-drawer a,.mobile-menu a').forEach(a=>{
      const href=(a.getAttribute('href')||'').replace(/\.html(?=($|#))/,'');
      if(href==='events'||href.startsWith('events#')) a.classList.add('active');
    });
  }
})();
